export {
  absoluteUrl,
  buildCanonicalUrl,
  createArticleJsonLd,
  createArticleMetadata,
  createBlogItemListJsonLd,
  createBreadcrumbJsonLd,
  createFaqPageJsonLd,
  createMetadata,
  createNoIndexMetadata,
  createOrganizationJsonLd,
  createWebsiteJsonLd,
  getSiteUrl,
  indexableRobots,
  noIndexRobots,
  rootMetadata,
} from "@/lib/seo/metadata";
